### ISSUE TITLE
[docker mysql 설치] docker-compse활용

### ISSUE THREAD

**Issue by forest-lim-dev** [forest-lim-dev/TIL#5]
# docker mysql 설치
## Env
- M1 Macbook Pro
- mysql Version 8.x

## docker-compose를 이용한 설치
```
version: "3"
services:
  db:
    image: mysql:8.0.29 # 사용할 이미지
    container_name: til_mysql
    ports:
      - "13306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/jiuklim/data:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    platform: linux/x86_64
```
